// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RcpgMicroserviceClient.Entities;
using System;

namespace RcpgMicroserviceClient.Migrations
{
    [DbContext(typeof(RcpgClientDbContext))]
    partial class RcpgClientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RcpgMicroserviceClient.Entities.Payment", b =>
                {
                    b.Property<string>("Token")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CapturedOn");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("InitiatedOn");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Sum");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(450);

                    b.HasKey("Token");

                    b.ToTable("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
